module.exports = {
  extends: ['stylelint-config-standard'],
  rules: {
    'at-rule-name-space-after': 'always',
    'at-rule-no-vendor-prefix': true,
    'at-rule-semicolon-space-before': 'never',
    'declaration-block-semicolon-newline-before': 'never-multi-line',
    'declaration-colon-space-after': 'always-single-line',
    'declaration-no-important': true,
    'declaration-property-value-blacklist': { '/^border/': ['none'] },
    'font-family-name-quotes': 'always-where-recommended',
    'font-weight-notation': ['numeric', { ignore: ['relative'] }],
    'function-parentheses-space-inside': 'never-single-line',
    'function-url-no-scheme-relative': true,
    'function-url-quotes': 'always',
    'indentation': 2,
    'media-feature-name-no-vendor-prefix': true,
    'no-descending-specificity': true,
    'no-duplicate-selectors': true,
    'no-empty-first-line': true,
    'property-no-vendor-prefix': true,
    'rule-empty-line-before': [
      'always',
      { ignore: ['after-comment', 'first-nested'] },
    ],
    'selector-attribute-quotes': 'always',
    'selector-list-comma-newline-before': 'never-multi-line',
    'selector-list-comma-space-after': 'always-single-line',
    'selector-list-comma-space-before': 'never-single-line',
    'selector-max-attribute': 2,
    'selector-max-class': 3,
    'selector-max-combinators': 3,
    'selector-max-compound-selectors': 3,
    'selector-max-id': 0,
    'selector-max-type': 2,
    'selector-max-universal': 1,
    'selector-no-qualifying-type': true,
    'selector-no-vendor-prefix': true,
    'shorthand-property-no-redundant-values': true,
    'string-quotes': 'double',
    'unicode-bom': 'never',
    'value-keyword-case': 'lower',
    'value-list-comma-space-after': 'always-single-line',
    'value-no-vendor-prefix': true,
  },
};
